### ISSUE TITLE
sucks

### ISSUE THREAD

**Issue by bravoalpha1** [tobiashuegle/smarthealthcard_mule#1]
your instructions suck!!  theyre just a summary...copy/paste crap...not actual instructions

**Comment by tobiashuegle** [comment]
The instructions summarise some key concepts of the SMART Health Card specification to provide context but then outline the workings of the attached Mule app. They assume a level of familiarity with MuleSoft and are to be used in context with the sample app to follow the implementation. They are not designed as a stand alone step by step instruction for creating smart health cards in MuleSoft. 

If you can provide some more specific / constructive feedback I'm happy to incorporate this.
